GET http://localhost:3000/api/diaries
###
POST http://localhost:3000/api/diaries
Content-Type: application/json

{
    "date": "2019-09-23",
    "weather": "sunny",
    "visibility": "ok",
    "comment": "Here lies Ilari, he reached the end doing what he loved"
}
