GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "First Blog",
    "author": "Arto Hellas",
    "url": "blogspot.com/aHellas234",
    "likes": 34
}
###
PUT http://localhost:3001/api/notes/60a943e1480f3c4cb0595932
Content-Type: application/json

{
    "content": "VS CODEEEEE",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/60a95acbead89e36cc0e8368