GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "First Blog",
    "author": "Arto Hellas",
    "url": "blogspot.com/aHellas234",
    "likes": 34
}
###
PUT http://localhost:3003/api/blogs/60b3c8d4c6d7582d90c98160
Content-Type: application/json

{
    "title": "First Blog",
    "author": "Arto Hellas",
    "url": "blogspot.com/aHellas234",
    "likes": 35
}

###
DELETE http://localhost:3003/api/blogs/60ac1203e6a4a640fc41e828